"""add default gravatar

Revision ID: 4372936f3760
Revises: f19f5af5c4c5
Create Date: 2022-11-16 15:50:06.011729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4372936f3760'
down_revision = 'f19f5af5c4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_gravatar', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_gravatar')
    # ### end Alembic commands ###
